package info5;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;

import org.gitlab4j.api.Constants;
import org.gitlab4j.api.GitLabApi;
import org.gitlab4j.api.GitLabApiException;
import org.gitlab4j.api.models.Project;
import org.gitlab4j.api.models.Visibility;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class Dashboard extends JFrame {

	private JPanel contentPane;
	static GitLabApi gitlabApi;
	static ArrayList<String> listpublicproject = new ArrayList<String>();
	static ArrayList<String> listprivateproject = new ArrayList<String>();
	static ArrayList<String> listownproject = new ArrayList<String>();
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Dashboard frame = new Dashboard(gitlabApi);			
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
    public Dashboard(GitLabApi gitLabApi) {
		gitlabApi = gitLabApi;
		initComponents();
		try {
			gitlabApi.getProjectApi().getProjects(false, Visibility.PRIVATE,Constants.ProjectOrderBy.NAME, Constants.SortOrder.ASC, null, false, false, false, false, true).forEach(project -> listprivateproject.add(project.getName()) );
			gitlabApi.getProjectApi().getProjects(false, Visibility.PUBLIC,Constants.ProjectOrderBy.NAME, Constants.SortOrder.ASC, null, false, false, false, false, true).forEach(project -> listpublicproject.add(project.getName()) );
			gitlabApi.getProjectApi().getProjects(false, null,Constants.ProjectOrderBy.NAME, Constants.SortOrder.ASC, null, false, false, true, false, true).forEach(project -> listownproject.add(project.getName()) );  
		} catch (GitLabApiException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
    
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        Button1.setBorder(null);
        Indicator1 = new javax.swing.JPanel();
        Indicator1.setBorder(new LineBorder(new Color(255, 255, 255)));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		Button1MouseClicked(e);
        	}
        });
        Button2 = new javax.swing.JPanel();
        Button2.setBorder(null);
        Indicator2 = new javax.swing.JPanel();
        Indicator2.setBorder(new LineBorder(new Color(0, 0, 0)));
        Indicator2.setForeground(Color.WHITE);
        jLabel2 = new javax.swing.JLabel();
        Button3 = new javax.swing.JPanel();
        Button3.setBorder(null);
        Indicator3 = new javax.swing.JPanel();
        Indicator3.setBorder(new LineBorder(Color.WHITE));
        Indicator3.setForeground(Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		Button3MouseClicked(e);
        	}
        });
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(41, 41, 97));

        Button1.setBackground(new java.awt.Color(208, 45, 26));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });

        Indicator1.setBackground(new java.awt.Color(255, 255, 255));
        Indicator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Indicator1Layout = new javax.swing.GroupLayout(Indicator1);
        Indicator1.setLayout(Indicator1Layout);
        Indicator1Layout.setHorizontalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator1Layout.setVerticalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout Button1Layout = new javax.swing.GroupLayout(Button1);
        Button1.setLayout(Button1Layout);
        Button1Layout.setHorizontalGroup(
            Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button1Layout.createSequentialGroup()
                .addComponent(Indicator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
        );
        Button1Layout.setVerticalGroup(
            Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Button1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Indicator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Button2.setBackground(new java.awt.Color(208, 45, 26));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2MouseExited(evt);
            }
        });

        Indicator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Indicator2Layout = new javax.swing.GroupLayout(Indicator2);
        Indicator2.setLayout(Indicator2Layout);
        Indicator2Layout.setHorizontalGroup(
            Indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator2Layout.setVerticalGroup(
            Indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Button2Layout = new javax.swing.GroupLayout(Button2);
        Button2Layout.setHorizontalGroup(
        	Button2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Button2Layout.createSequentialGroup()
        			.addComponent(Indicator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 92, Short.MAX_VALUE))
        );
        Button2Layout.setVerticalGroup(
        	Button2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, Button2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        			.addContainerGap())
        		.addComponent(Indicator2, GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        Button2.setLayout(Button2Layout);

        Button3.setBackground(new java.awt.Color(208, 45, 26));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button3MouseExited(evt);
            }
        });

        Indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Indicator3Layout = new javax.swing.GroupLayout(Indicator3);
        Indicator3.setLayout(Indicator3Layout);
        Indicator3Layout.setHorizontalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator3Layout.setVerticalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Statistics");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout Button3Layout = new javax.swing.GroupLayout(Button3);
        Button3.setLayout(Button3Layout);
        Button3Layout.setHorizontalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button3Layout.createSequentialGroup()
                .addComponent(Indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Button3Layout.setVerticalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Button3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setIcon(new javax.swing.ImageIcon("src/main/java/info5/assets/logo.png"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jLabel12)
        			.addGap(0, 48, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Button1, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        				.addComponent(Button3, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Button2, GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(86, Short.MAX_VALUE)
        			.addComponent(jLabel12)
        			.addGap(59)
        			.addComponent(Button1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(Button2, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        			.addGap(21)
        			.addComponent(Button3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(158))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        
        JLabel jLabel5_1 = new JLabel();
        jLabel5_1.setToolTipText("");
        jLabel5_1.setText("Welcome to your Dashboard GitLab");
        jLabel5_1.setForeground(new Color(41, 41, 97));
        jLabel5_1.setFont(new Font("Segoe UI", Font.BOLD, 24));
        
        String[] array1 = listpublicproject.toArray(new String[listpublicproject.size()]);
        String[] array2 = listprivateproject.toArray(new String[listprivateproject.size()]);
        String[] array3 = listownproject.toArray(new String[listownproject.size()]);
        
        panel_1 = new JPanel();
        panel_1.setLayout(null);
        
        panel_2 = new JPanel();
        panel_2.setLayout(null);
        
        scrollPane = new JScrollPane();
        scrollPane.setBounds(10, 3, 282, 130);
        
        scrollPane_1 = new JScrollPane();
        scrollPane_1.setBounds(10, 3, 282, 130);

        JList list = new JList(array1);
        scrollPane.setViewportView(list);
        list.setBounds(10, 5, 267, 128);
        panel_1.add(scrollPane);
        
        JList list2 = new JList(array2);
        scrollPane_1.setViewportView(list2);
        list2.setBounds(10, 5, 267, 128);
        panel_2.add(scrollPane_1);
        list2.setBounds(10, 5, 267, 128);
        
        setTitle("JTable basique dans un JScrollPane");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 
        Object[][] donnees = {
        		{"Nom", "Membres", "Date de création", "Module", "Archivé"},
                {"Johnathan", "Sykes", "red", true, "TENNIS"},
                {"Nicolas", "Van de Kampf", "black", true, "FOOTBALL"},
                {"Damien", "Cuthbert", "cyan", true, "RIEN"},
                {"Corinne", "Valance", "blue", false, "NATATION"},
                {"Emilie", "Schrödinger", "magenta", false, "FOOTBALL"},
                {"Delphine", "Duke", "yellow", false, "TENNIS"},
                {"Eric", "Trump", "pink", true, "FOOTBALL"}
        };
 
        String[] entetes = {"Nom", "Membres", "Date de création", "Module", "Archivé"};        
        table = new JTable(donnees, entetes);        
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(table, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        					.addGap(21)
        					.addComponent(jLabel5_1, GroupLayout.PREFERRED_SIZE, 430, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(panel_2, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(jLabel5_1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(panel_2, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        				.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
        			.addGap(36)
        			.addComponent(table, GroupLayout.PREFERRED_SIZE, 353, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Button3MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator3,jLabel3);
        onleaveHover(Indicator2,jLabel2);
        onleaveHover(Indicator1,jLabel1);
    }                                    

    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {
    	Statistics statistiques = new Statistics(gitlabApi);
    	this.setVisible(false);
    	statistiques.setVisible(true);
    }   

    private void Button2MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button2MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator2,jLabel2);
        onleaveHover(Indicator1,jLabel1);
        onleaveHover(Indicator3,jLabel3);
    }                                    

    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {           
    }                                    

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     

    }                                    

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator1,jLabel1);
        onleaveHover(Indicator3,jLabel3);
        onleaveHover(Indicator2,jLabel2);
    }
    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {
    	Home home = new Home(gitlabApi);
    	this.setVisible(false);
    	home.setVisible(true);
    }                                    
    private void onHover(JPanel panel,JLabel label){
         panel.setBackground(new Color(0,0,0));
         panel.setBorder(new LineBorder(new Color(0, 0, 0)));
         panel.setForeground(new Color(0,0,0));
         label.setForeground(new Color(0,0,0));
    }
    private void onleaveHover(JPanel panel,JLabel label){
         panel.setBackground(new Color(255,255,255));
         panel.setBorder(new LineBorder(new Color(255, 255, 255)));
         label.setForeground(new Color(255,255,255));
    }
    private void onClick(JPanel panel,JLabel label){
         panel.setBackground(new Color(0,0,0));
         label.setForeground(new Color(0,0,0));
    }
    private void onleaveClick(JPanel panel,JLabel label){
         panel.setBackground(new Color(255,255,255));
         label.setForeground(new Color(255,255,255));
    }
    private void hiddenpanel(JPanel panel){
    panel.setVisible(false);
    }
    // Variables declaration - do not modify                     
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel Button2;
    private javax.swing.JPanel Button3;
    private javax.swing.JPanel Indicator1;
    private javax.swing.JPanel Indicator2;
    private javax.swing.JPanel Indicator3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JPanel panel_2;
    private JScrollPane scrollPane_1;
    private JPanel panel_1;
    private JScrollPane scrollPane;
    private JTable table;
}
