package info5;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFileChooser;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import org.gitlab4j.api.Constants;
import org.gitlab4j.api.GitLabApi;
import org.gitlab4j.api.GitLabApiException;
import org.gitlab4j.api.models.Project;
import org.gitlab4j.api.models.TreeItem;
import org.gitlab4j.api.models.Visibility;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import info5.API.ImportCSV;
import javax.swing.JTree;

public class Home extends JFrame {
   
	private JPanel contentPane;
	static GitLabApi gitlabApi;
	private List<Project> projectlist;
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Home frame = new Home(gitlabApi);
					frame.setVisible(true);} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
    public Home(GitLabApi gitLabApi) {
    	gitlabApi=gitLabApi;
    	try {
			projectlist = gitlabApi.getProjectApi().getProjects(false, Visibility.PRIVATE,Constants.ProjectOrderBy.NAME, Constants.SortOrder.ASC, null, false, false, false, false, true);
    	} catch (GitLabApiException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        initComponents();
    }
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        Button1.setBorder(null);
        Indicator1 = new javax.swing.JPanel();
        Indicator1.setBorder(new LineBorder(new Color(0, 0, 0)));
        jLabel1 = new javax.swing.JLabel();
        Button2 = new javax.swing.JPanel();
        Button2.setBorder(null);
        Indicator2 = new javax.swing.JPanel();
        Indicator2.setBorder(new LineBorder(new Color(255, 255, 255)));
        Indicator2.setForeground(Color.WHITE);
        jLabel2 = new javax.swing.JLabel();
        Button3 = new javax.swing.JPanel();
        Button3.setBorder(null);
        Indicator3 = new javax.swing.JPanel();
        Indicator3.setBorder(new LineBorder(Color.WHITE));
        Indicator3.setForeground(Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		Button3MouseClicked(e);
        	}
        });
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();


        jPanel1.setBackground(new java.awt.Color(41, 41, 97));

        Button1.setBackground(new java.awt.Color(208, 45, 26));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });

        Indicator1.setBackground(new java.awt.Color(0, 0, 0));
        Indicator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Indicator1Layout = new javax.swing.GroupLayout(Indicator1);
        Indicator1.setLayout(Indicator1Layout);
        Indicator1Layout.setHorizontalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator1Layout.setVerticalGroup(
            Indicator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jLabel1.setToolTipText("");

        Button2.setBackground(new java.awt.Color(208, 45, 26));
        Button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2MouseExited(evt);
            }
        });

        Indicator2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Indicator2Layout = new javax.swing.GroupLayout(Indicator2);
        Indicator2.setLayout(Indicator2Layout);
        Indicator2Layout.setHorizontalGroup(
            Indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator2Layout.setVerticalGroup(
            Indicator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	Button2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Button2Layout = new javax.swing.GroupLayout(Button2);
        Button2Layout.setHorizontalGroup(
        	Button2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Button2Layout.createSequentialGroup()
        			.addComponent(Indicator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 92, Short.MAX_VALUE))
        );
        Button2Layout.setVerticalGroup(
        	Button2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, Button2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        			.addContainerGap())
        		.addComponent(Indicator2, GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
        Button2.setLayout(Button2Layout);

        Button3.setBackground(new java.awt.Color(208, 45, 26));
        Button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button3MouseExited(evt);
            }
        });

        Indicator3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Indicator3Layout = new javax.swing.GroupLayout(Indicator3);
        Indicator3.setLayout(Indicator3Layout);
        Indicator3Layout.setHorizontalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Indicator3Layout.setVerticalGroup(
            Indicator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Statistics");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout Button3Layout = new javax.swing.GroupLayout(Button3);
        Button3.setLayout(Button3Layout);
        Button3Layout.setHorizontalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button3Layout.createSequentialGroup()
                .addComponent(Indicator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Button3Layout.setVerticalGroup(
            Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Indicator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Button3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setIcon(new javax.swing.ImageIcon("src/main/java/info5/assets/logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jLabel12)
        			.addGap(0, 38, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(Button1, GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        				.addComponent(Button3, GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(Button2, GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(86)
        			.addComponent(jLabel12)
        			.addGap(59)
        			.addComponent(Button1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(21)
        			.addComponent(Button2, GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(Button3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(158))
        );
        GroupLayout gl_Button1 = new GroupLayout(Button1);
        gl_Button1.setHorizontalGroup(
        	gl_Button1.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_Button1.createSequentialGroup()
        			.addComponent(Indicator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
        );
        gl_Button1.setVerticalGroup(
        	gl_Button1.createParallelGroup(Alignment.LEADING)
        		.addComponent(Indicator1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        		.addGroup(gl_Button1.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        );
        Button1.setLayout(gl_Button1);
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 41, 97));
        jLabel5.setText("Import CSV");
        jLabel5.setToolTipText("");
        
        
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setBounds(100, 100, 450, 300);
        JButton btnNewButton = new JButton("Import");
        btnNewButton.setForeground(new java.awt.Color(41, 41, 97));
        btnNewButton.setBackground(Color.WHITE);
        jfc.setVisible(false);
        
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                // component d'import de fichier csv 
        		jfc.setVisible(true);
        		int returnValue = jfc.showOpenDialog(null);
        		if (returnValue == JFileChooser.APPROVE_OPTION) {
        			File selectedFile = jfc.getSelectedFile();
        			//ArrayList that contains all the informations
        			ArrayList <String[]> status=new ArrayList <String[]>();
        			//(PathOfCSV,GitLabAPI,host(code.telecom.tse by default),token for api if connection by token)
        		    status = ImportCSV.ImportProjectsMembers(selectedFile.getAbsolutePath(),gitlabApi,null,null);  
        		    System.out.println(status);
        		    ImportCSVInfo.main(status);
        		}	
        	}
        });
        
        JLabel lblGitlabArborescence = new JLabel();
        lblGitlabArborescence.setToolTipText("");
        lblGitlabArborescence.setText("Arborescence Gitlab ");
        lblGitlabArborescence.setForeground(new Color(41, 41, 97));
        lblGitlabArborescence.setFont(new Font("Segoe UI", Font.BOLD, 24));
        DefaultMutableTreeNode Gitroot = new DefaultMutableTreeNode("Gitlab");
        for (ListIterator<Project> iter = projectlist.listIterator(); iter.hasNext(); ) {
        			Project element = iter.next();
        			DefaultMutableTreeNode temp = new DefaultMutableTreeNode(element.getName());
        			try {
        				gitlabApi.getRepositoryApi().getTree(element.getId()).forEach(name -> temp.add(new DefaultMutableTreeNode(name.getName())));
					} catch (Exception e) {
						// TODO Auto-generated catch block
						System.out.println(e);
					}
                    Gitroot.add(temp);
        }

        DefaultTreeModel treeModel = new DefaultTreeModel(Gitroot);
        JTree tree = new JTree(treeModel);
        tree.setBackground(null);
        
        jLabel12_1 = new JLabel();
        jLabel12_1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		tree.clearSelection();
        		try {
					projectlist = gitlabApi.getProjectApi().getProjects(false, Visibility.PRIVATE,Constants.ProjectOrderBy.NAME, Constants.SortOrder.ASC, null, false, false, false, false, true);
					System.out.println(projectlist.size());
				} catch (GitLabApiException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}           	
                DefaultMutableTreeNode Gitroot = new DefaultMutableTreeNode("Gitlab");
                for (ListIterator<Project> iter = projectlist.listIterator(); iter.hasNext(); ) {
                			Project element = iter.next();
                			DefaultMutableTreeNode temp = new DefaultMutableTreeNode(element.getName());
                			try {
                				gitlabApi.getRepositoryApi().getTree(element.getId()).forEach(name -> temp.add(new DefaultMutableTreeNode(name.getName())));
        					} catch (Exception d ) {
        						// TODO Auto-generated catch block
        						System.out.println(d);
        					}
                            Gitroot.add(temp);
                }
                treeModel.setRoot(Gitroot);
                treeModel.reload();
        	}
        });
        jLabel12_1.setIcon(new javax.swing.ImageIcon("src/main/java/info5/assets/icons/refresh.png"));
        
        
        
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblGitlabArborescence, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addGap(102)
        							.addComponent(btnNewButton))))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(32)
        					.addComponent(tree, GroupLayout.PREFERRED_SIZE, 217, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel12_1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton))
        			.addGap(51)
        			.addComponent(lblGitlabArborescence, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(tree, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12_1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Button3MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator3,jLabel3);
        onleaveHover(Indicator2,jLabel2);
        onleaveHover(Indicator1,jLabel1);
    }  
    
    private void Button3MouseClicked(java.awt.event.MouseEvent evt) {  
    	Statistics statistiques = new Statistics(gitlabApi);
    	this.setVisible(false);
    	statistiques.setVisible(true);
    }                                    

    private void Button2MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button2MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator2,jLabel2);
        onleaveHover(Indicator1,jLabel1);
        onleaveHover(Indicator3,jLabel3);
    }                                    
    
    private void Button2MouseClicked(java.awt.event.MouseEvent evt) {     
    	Dashboard dashboard = new Dashboard(gitlabApi);
    	this.setVisible(false);
    	dashboard.setVisible(true);
    }                                    
                                   

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {                                    

    }                                   

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {                                     
        onHover(Indicator1,jLabel1);
        onleaveHover(Indicator3,jLabel3);
        onleaveHover(Indicator2,jLabel2);
    }                                    

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {

    	
    }   
    
    
    private void onHover(JPanel panel,JLabel label){
         panel.setBackground(new Color(0,0,0));
         panel.setBorder(new LineBorder(new Color(0, 0, 0)));
         panel.setForeground(new Color(0,0,0));
         label.setForeground(new Color(0,0,0));
    }
    private void onleaveHover(JPanel panel,JLabel label){
         panel.setBackground(new Color(255,255,255));
         panel.setBorder(new LineBorder(new Color(255, 255, 255)));
         label.setForeground(new Color(255,255,255));
    }
    private void onleaveClick(JPanel panel,JLabel label){
         panel.setBackground(new Color(255,255,255));
         label.setForeground(new Color(255,255,255));
    }
    private void hiddenpanel(JPanel panel){
    panel.setVisible(false);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel Button2;
    private javax.swing.JPanel Button3;
    private javax.swing.JPanel Indicator1;
    private javax.swing.JPanel Indicator2;
    private javax.swing.JPanel Indicator3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFileChooser jfc;
    private JLabel jLabel12_1;
    private JTree tree;
    private DefaultTreeModel treeModel;
}
